events {
        worker_connections 1024;
}

user lett; # update this to the user that owners the directory specified in the root directive.

http {
        server {
                listen       8080;
                server_name  localhost;
                root /home/lett/PycharmProjects/MDNWebsite/; # wherever the git root is.

                location = / {
                        include /etc/nginx/mime.types;
                        try_files /templates/index.html =404;
                }

                location /static {
                        include  /etc/nginx/mime.types;
                        try_files $uri $uri =404;
                }

                location = /favicon.ico {
                        include /etc/nginx/mime.types;
                        try_files /static/logo.png =404;
                }


                location / {
                        include  /etc/nginx/mime.types;
                        try_files $uri.html /templates$uri;
                        index /templates/index.html;
                }
        }
}
